import sqlite3,tempfile,sys,unittest
from pathlib import Path
sys.path.insert(0,str(Path(__file__).parents[1]/'src'))
import revenue_media_os.core as core
from revenue_media_os.core import *
from revenue_media_os.providers import PublisherRouter,WordPressPublisher,ProviderResult,OpenSERPProvider,GoogleAPIProvider
REAL={'search_gap':'PASS','competition':'PASS','historical_revenue':'CONFIGURED_NO_DATA','site_fit':'PASS','country_fit':'PASS','freshness':'PASS','risk':'PASS','cost':'PASS'}
class T(unittest.TestCase):
 def setUp(self): self.db=IntelligenceDB()
 def tearDown(self): self.db.close()
 def pub(self,k='x'):
  s=TrendSensor(self.db).ingest(k,'fixture',[30,60,90,120,180]); o=OpportunityEngine(self.db).decide(s,mode='FIXTURE'); site=self.db.site(tenant_id='t',country='US',language='en',topic='ai coding',platform='local',authority_tags='ai,coding',health_status='GOOD',policy_status='CLEAN'); e=Editorial(self.db); p=e.plan(o,site,'MONEY',[],'info',[]); c=e.article(p,'t','b'); pub=LocalPublisher(self.db).publish(c,site,tempfile.mkdtemp()); kid=self.db.conn.execute('select keyword_id from opportunities where id=?',(o,)).fetchone()[0]; return s,o,site,c,pub,kid
 def test_keyword_key(self): self.assertEqual(len({self.db.keyword('GPT',c,l) for c,l in [('US','en'),('KR','ko'),('JP','ja')]}),3)
 def test_missing_not_zero(self):
  s=TrendSensor(self.db).ingest('m','api',mention_count=None,unique_authors=None,engagement=None,observed_at='2026-08-28T10:00:00+00:00',status='MISSING'); r=self.db.conn.execute('select * from signals where id=?',(s,)).fetchone(); self.assertIsNone(r['mention_count']); self.assertEqual(r['status'],'MISSING')
 def test_real_velocity_current_bucket(self):
  ts=TrendSensor(self.db); ts.ingest('v','api',mention_count=10,unique_authors=2,engagement=3,observed_at='2026-08-28T09:00:00+00:00',status='OBSERVED'); s=ts.ingest('v','api',mention_count=20,unique_authors=3,engagement=4,observed_at='2026-08-28T10:00:00+00:00',status='OBSERVED'); r=self.db.conn.execute('select * from signals where id=?',(s,)).fetchone(); self.assertEqual((r['velocity_1h'],r['velocity_3h'],r['acceleration']),(20,15,5))
 def test_real_missing_blocks_write(self):
  s=TrendSensor(self.db).ingest('r','fixture',[50,90,120,160,200]); o=OpportunityEngine(self.db).decide(s,mode='REAL',risk=.1,input_statuses={'risk':'PASS'}); self.assertEqual(self.db.conn.execute('select decision from opportunities where id=?',(o,)).fetchone()[0],'WATCH')
 def test_unknown_risk_review(self):
  s=TrendSensor(self.db).ingest('r2','fixture',[50,90,120,160,200]); o=OpportunityEngine(self.db).decide(s,mode='REAL'); self.assertEqual(self.db.conn.execute('select decision from opportunities where id=?',(o,)).fetchone()[0],'REVIEW_REQUIRED')
 def test_high_risk_review(self):
  s=TrendSensor(self.db).ingest('fin','fixture',[50,90,120,160,200]); o=OpportunityEngine(self.db).decide(s,mode='REAL',search_gap=1,competition=.1,historical_revenue=0,site_fit=1,country_fit=1,freshness=1,risk=.1,cost=.1,input_statuses=REAL,risk_class='FINANCE'); self.assertEqual(self.db.conn.execute('select decision from opportunities where id=?',(o,)).fetchone()[0],'REVIEW_REQUIRED')
 def test_fast_signal_not_fast_write(self):
  s=TrendSensor(self.db).ingest('fast','fixture',[50,90,120,160,200]); self.assertEqual(self.db.conn.execute('select is_fast_candidate from signals where id=?',(s,)).fetchone()[0],1); o=OpportunityEngine(self.db).decide(s,mode='REAL',search_gap=.1,competition=.1,historical_revenue=0,site_fit=1,country_fit=1,freshness=1,risk=.1,cost=.1,input_statuses=REAL); self.assertNotEqual(self.db.conn.execute('select decision from opportunities where id=?',(o,)).fetchone()[0],'FAST_WRITE')
 def test_telemetry_separated(self):
  *_,pub,kid=self.pub('tele'); Telemetry(self.db).record(pub,kid,rank=3,search={'impressions':100,'clicks':10},analytics={'sessions':8},revenue={'adsense_revenue':1.2},rank_status='PASS',search_console_status='PASS',analytics_status='NOT_CONFIGURED',revenue_status='CONFIGURED_NO_DATA'); self.assertEqual(self.db.conn.execute('select provider_status from search_metrics').fetchone()[0],'PASS'); self.assertEqual(self.db.conn.execute('select provider_status from analytics_metrics').fetchone()[0],'NOT_CONFIGURED'); self.assertEqual(provider_status_summary(self.db)['overall'],'PARTIAL')
 def test_site_fit_all_candidates(self):
  ai=self.db.site(tenant_id='t',country='US',language='en',topic='ai coding',platform='local',authority_tags='ai,coding,agent',average_revenue=10,average_rpm=5,health_status='GOOD',policy_status='CLEAN'); self.db.site(tenant_id='t',country='US',language='en',topic='finance loans',platform='local',authority_tags='finance,loans',average_revenue=100,average_rpm=20,health_status='GOOD',policy_status='CLEAN'); r=PublisherRouter(self.db).select_site_result('ai coding agent','US','en','ai coding',['ai','coding']); self.assertEqual(r['site']['id'],ai); self.assertEqual(len(r['candidate_scores']),2)
 def test_router_single(self): self.assertFalse(hasattr(core,'PublisherRouter'))
 def test_cost_no_double_scope_and_profit(self):
  _,o,_,c,pub,kid=self.pub('cost'); t=Telemetry(self.db); self.assertRaises(ValueError,t.record_cost,'bad','x',amount=1,opportunity_id=o,content_id=c); t.record_cost('serp','x',amount=.1,opportunity_id=o); t.record_cost('writer','x',amount=.2,content_id=c); t.record_cost('publish','x',amount=.3,publication_id=pub); t.record(pub,kid,revenue={'adsense_revenue':2},revenue_status='PASS'); self.assertAlmostEqual(content_economics(self.db,c)['contribution_profit'],1.4)
 def test_timezone_windows(self):
  self.db.set_config('report_timezone','Asia/Seoul'); self.assertEqual(daily_report(self.db,'2026-08-28')['period_start'],'2026-08-28'); self.db.set_config('report_timezone','America/New_York'); self.assertEqual(daily_report(self.db,'2026-11-01')['period_end'],'2026-11-01'); self.assertEqual(period_report(self.db,'monthly','2026-08-28')['window_type'],'rolling_30d')
 def test_wordpress_validation_and_unconfigured(self): self.assertEqual(WordPressPublisher.validate_post_response(ProviderResult('PASS',{'id':1,'link':'https://x','status':'publish'})).status,'PASS'); self.assertEqual(WordPressPublisher.validate_post_response(ProviderResult('PASS',{'id':1})).status,'FAIL'); self.assertEqual(OpenSERPProvider().search('x').status,'NOT_CONFIGURED'); self.assertEqual(GoogleAPIProvider(None).query('x').status,'NOT_CONFIGURED')
 def test_schema_fk(self): self.assertEqual(self.db.conn.execute('select max(version) from schema_version').fetchone()[0],3); self.assertEqual(self.db.conn.execute('pragma foreign_keys').fetchone()[0],1); self.assertEqual(self.db.conn.execute('pragma foreign_key_check').fetchall(),[])
 def test_old_db_migration(self):
  with tempfile.TemporaryDirectory() as td:
   p=str(Path(td)/'old.db'); c=sqlite3.connect(p); c.executescript("""PRAGMA foreign_keys=ON; CREATE TABLE keywords(id INTEGER PRIMARY KEY,keyword TEXT NOT NULL UNIQUE,country TEXT NOT NULL,language TEXT NOT NULL,created_at TEXT NOT NULL); CREATE TABLE signals(id INTEGER PRIMARY KEY,keyword_id INTEGER NOT NULL REFERENCES keywords(id),source TEXT NOT NULL,country TEXT NOT NULL,language TEXT NOT NULL,mention_count INTEGER NOT NULL,unique_authors INTEGER NOT NULL,engagement INTEGER NOT NULL,velocity_1h REAL NOT NULL,velocity_3h REAL NOT NULL,velocity_6h REAL NOT NULL,velocity_12h REAL NOT NULL,velocity_24h REAL NOT NULL,acceleration REAL NOT NULL,platform_count INTEGER NOT NULL DEFAULT 1,country_count INTEGER NOT NULL DEFAULT 1,first_seen_at TEXT NOT NULL,last_seen_at TEXT NOT NULL,is_fast_candidate INTEGER NOT NULL DEFAULT 0); CREATE TABLE opportunities(id INTEGER PRIMARY KEY,keyword_id INTEGER NOT NULL REFERENCES keywords(id),signal_id INTEGER REFERENCES signals(id),decision TEXT NOT NULL,score REAL NOT NULL,decision_reason TEXT NOT NULL,score_components TEXT NOT NULL,engine_version TEXT NOT NULL,created_at TEXT NOT NULL); CREATE TABLE cost_metrics(id INTEGER PRIMARY KEY,component TEXT NOT NULL,provider TEXT NOT NULL,input_tokens INTEGER NOT NULL DEFAULT 0,output_tokens INTEGER NOT NULL DEFAULT 0,amount REAL NOT NULL DEFAULT 0,currency TEXT NOT NULL DEFAULT 'USD',captured_at TEXT NOT NULL,status TEXT NOT NULL); INSERT INTO keywords VALUES(1,'GPT','US','en','2026-08-28T00:00:00+00:00'); INSERT INTO signals VALUES(1,1,'fixture','US','en',5,2,9,5,2,1,.5,.2,3,1,1,'2026-08-28T00:00:00+00:00','2026-08-28T00:00:00+00:00',0); INSERT INTO opportunities VALUES(1,1,1,'WATCH',.1,'old','{}','Opportunity-v1','2026-08-28T00:00:00+00:00'); INSERT INTO cost_metrics VALUES(1,'writer','local',0,0,.1,'USD','2026-08-28T00:00:00+00:00','PASS');"""); c.commit(); c.close(); d=IntelligenceDB(p); self.assertEqual(d.conn.execute('pragma foreign_key_check').fetchall(),[]); self.assertEqual(d.conn.execute('pragma foreign_keys').fetchone()[0],1); self.assertNotEqual(d.keyword('GPT','KR','ko'),1); self.assertIn(('observation_id','signal_observations','id'),{(r[3],r[2],r[4]) for r in d.conn.execute('pragma foreign_key_list(signals)')}); d.close()
if __name__=='__main__': unittest.main()
